name: gkit-build-test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug, Release]
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl3-dev cmake build-essential

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install sdl3
        choco install cmake
        choco install ninja

    # - name: Install dependencies (macOS)
    #   if: runner.os == 'macOS'
    #   run: |
    #     brew install sdl3
    #     brew install cmake

    - name: Configure CMake (Linux)
      if: runner.os == 'Linux'
      run: |
        cmake --preset linux-x86_64-gcc-debug

    - name: Configure and build project (Linux)
      run: cmake --build ${{ github.workspace }}/build/linux-x86_64-gcc-debug

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: gkit-${{ matrix.os }}-${{ matrix.build_type }}
        path: ${{ github.workspace }}/build/